<?php

namespace JackAssPHP\Helper;

require_once dirname(__FILE__) . '/../../../JackAssPHP/Helper/Filter.php';

/**
 * Test class for Filter.
 * Generated by PHPUnit on 2012-08-05 at 17:15:46.
 */
class FilterTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Filter
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp ()
    {
        $this->object = new Filter;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown ()
    {

    }

    /**
     * @covers JackAssPHP\Helper\Filter::validateEmail
     * @todo Implement testValidateEmail().
     */
    public function testValidateEmail ()
    {
        $true[] = "daniel@xebro.de";
        $true[] = "dan-iel@xebro.org";
        $true[] = "dan.iel@xebro.de";
        $true[] = "igor@loot-manager.com";
        $true[] = "igor@subdomain.loot-manager.com";

        foreach ($true as $email) {
            $this->assertSame(true, \JackAssPHP\Helper\Filter::validateEmail($email));
        }

        $false[] = "";
        $false[] = "da/niel@test.de";
        $false[] = "dan?iel@test.de";

        foreach ($false as $email) {
            $this->assertSame(false, \JackAssPHP\Helper\Filter::validateEmail($email));
        }
    }

    public function testIp ()
    {
        $true[] = "192.168.0.1";
        $true[] = "127.0.0.1";

        foreach ($true as $ip) {
            $this->assertSame(true, \JackAssPHP\Helper\Filter::validateIp($ip));
        }

        $false[] = "01.168.0.1";
        $false[] = "01.168.0.1.1";

        foreach ($false as $ip) {
            $this->assertSame(false, \JackAssPHP\Helper\Filter::validateIp($ip));
        }
    }

}

?>
