<?php

namespace JackAssPHP\Helper;

require_once dirname(__FILE__) . '/../../../JackAssPHP/Helper/Rights.php';

/**
 * Test class for Rights.
 * Generated by PHPUnit on 2012-01-25 at 16:44:12.
 */
class RightsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Rights
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp ()
    {
        $this->object = new Rights;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown ()
    {
        
    }

    /**
     * @covers {className}::{origMethodName}
     * @todo Implement testSetRight().
     */
    public function testSetRight ()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers {className}::{origMethodName}
     * @todo Implement testRemoveRight().
     */
    public function testRemoveRight ()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers {className}::{origMethodName}
     * @todo Implement testHasRight().
     */
    public function testHasRight ()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
