<?php

namespace JackAssPHP\Core;

require_once dirname(__FILE__) . '/../../../JackAssPHP/Core/Registry.php';

/**
 * Test class for Registry.
 * Generated by PHPUnit on 2012-01-18 at 21:31:25.
 */
class RegistryTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Registry
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp ()
    {
        $this->object = new Registry;
    }

    /**
     * @covers Registry::set
     * @covers Registry::get
     */
    public function testSetAndGet ()
    {
       $value = 1234;
       $name = "name";
       
       $this->object->set($name, $value);
       
       $this->assertSame($value, $this->object->get($name));
    }
}

?>
